plugins {
    id 'net.fabricmc.fabric-loom' version '1.17.0-alpha.13'
    id 'com.gradleup.shadow'
    id 'maven-publish'
}

base {
    archivesName = "$rootProject.archives_name-$project.name"
}

repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
    maven {
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        name "IzzelAliz Maven"
        url "https://maven.izzel.io/releases/"
    }
    maven {
        name "JitPack"
        url 'https://jitpack.io'
    }
    maven {
        name "dv8tion"
        url "https://m2.dv8tion.net/releases"
    }
    flatDir {
        dir rootProject.file('libs')
    }
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"

    implementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    implementation "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"

    common project(':common')
    shadowBundle (project(':common')) {transitive = false}

    implementation "com.terraformersmc:modmenu:$rootProject.modmenu_version"

    implementation("icyllis.modernui:ModernUI-Fabric:26.1.2-${rootProject.modernui_version}.+")

    implementation "com.sedmelluq:lavaplayer:$rootProject.lavaplayer_version"
    shadowBundle "com.sedmelluq:lavaplayer:$rootProject.lavaplayer_version"

//    implementation "io.github.selemba1000:JavaMediaTransportControls:$rootProject.jmtc_version"
//    shadowBundle "io.github.selemba1000:JavaMediaTransportControls:$rootProject.jmtc_version"
    implementation "com.github.hypfvieh:dbus-java-core:$rootProject.dbus_version"
    shadowBundle "com.github.hypfvieh:dbus-java-core:$rootProject.dbus_version"
    implementation "com.github.hypfvieh:dbus-java-transport-native-unixsocket:$rootProject.dbus_version"
    shadowBundle "com.github.hypfvieh:dbus-java-transport-native-unixsocket:$rootProject.dbus_version"

    compileOnly "org.projectlombok:lombok:$rootProject.lombok_version"
    annotationProcessor "org.projectlombok:lombok:$rootProject.lombok_version"
    testCompileOnly "org.projectlombok:lombok:$rootProject.lombok_version"
    testAnnotationProcessor "org.projectlombok:lombok:$rootProject.lombok_version"
    testImplementation "org.junit.jupiter:junit-jupiter:$rootProject.junit_version"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

sourceSets {
    main {
        resources {
            srcDir project(':common').file('src/main/resources')
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand version: inputs.properties.version
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
    exclude 'org/slf4j/**'
}

jar {
    dependsOn shadowJar
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from(zipTree(shadowJar.archiveFile))
}

loom {
    runs {
        client {
            runDir = "run/client"
        }
        server {
            runDir = "run/server"
        }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = base.archivesName.get()
            from components.java
        }
    }
}
