pluginManagement {
    repositories {
        maven { url = 'https://repo.papermc.io/repository/maven-public/' }
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    }
}

rootProject.name = 'music_hud'

include 'core'
include 'paper'
include 'velocity'
