architectury {
    common rootProject.architectury_enabled_platforms.split(',')
}

repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
    maven {
        name = 'dv8tion'
        url = 'https://m2.dv8tion.net/releases'
    }
}

processResources {
    dependsOn(rootProject.tasks.named('generateUiIcons'))
    inputs.property("version", rootProject.version)
    filteringCharset "UTF-8"

    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    from(sourceSets.main.resources.srcDirs) {
        exclude "META-INF/mods.toml"
        exclude "fabric.mod.json"
    }
    from(rootProject.file('common/build/generated/resources/platform-icons')) {
        into 'assets/music_hud/textures/gui/icons'
    }
}

dependencies {
    api project(':core')

    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    // Use Neoforge to avoid "Type net/neoforged/api/distmarker/Dist not present"
    modImplementation "net.neoforged:mergetool:2.0.0"

    testImplementation "org.junit.jupiter:junit-jupiter:$rootProject.junit_version"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
    compileOnly "icyllis.modernui:ModernUI-NeoForge:1.21.8-$rootProject.modernui_version.+"

    implementation "com.sedmelluq:lavaplayer:$rootProject.lavaplayer_version"
    implementation "com.github.hypfvieh:dbus-java-core:$rootProject.dbus_version"
    implementation "com.github.hypfvieh:dbus-java-transport-native-unixsocket:$rootProject.dbus_version"
}

test {
    useJUnitPlatform()
    enabled = false
}

shadowJar {
    enabled = false
}
