modLoader = "javafml"
loaderVersion = "[9,)"
issueTrackerURL = "https://github.com/Etern-34520/MusicHud/issues"
license = "LGPL-3.0"

[[mods]]
modId = "music_hud"
version = "${version}"
displayName = "Music Hud"
authors = "Etern"
description = "Request music in whole server powered by Netease Cloud Music (NCM) | 一个基于网易云的全服点歌模组"
displayURL = "https://github.com/Etern-34520/MusicHud"
logoFile = "assets/music_hud/icon.png"

[[dependencies.music_hud]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.music_hud]]
modId = "minecraft"
type = "required"
versionRange = "1.21.11"
ordering = "NONE"
side = "BOTH"

[[dependencies.music_hud]]
modId = "modernui"
type = "required"
versionRange = "[3.12.0.5,)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "music_hud.mixins.json"