plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
    id 'com.gradleup.shadow'
}

base {
    archivesName = "$rootProject.archives_name-$project.name"
}

sourceSets {
    main {
        java {
            srcDir project(':common').file('src/main/java')
        }
        resources {
            srcDir project(':common').file('src/main/resources')
        }
    }
}

repositories {
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
    maven {
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        name "JitPack"
        url 'https://jitpack.io'
    }
    maven {
        name "IzzelAliz Maven"
        url "https://maven.izzel.io/releases/"
    }
    maven {
        name "dv8tion"
        url "https://m2.dv8tion.net/releases"
    }
    flatDir {
        dir rootProject.file('libs')
    }
}

configurations {
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

neoForge {
    version = rootProject.neoforge_version

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        "$rootProject.archives_name" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    compileOnly "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    implementation("icyllis.modernui:ModernUI-NeoForge:26.2-${rootProject.modernui_version}.+")
    implementation("dev.icyllis:modernui-core:$rootProject.modernui_version") {
        exclude group: "org.slf4j", module: "slf4j-api"
        exclude group: "org.apache.logging.log4j", module: "log4j-core"
        exclude group: "org.apache.logging.log4j", module: "log4j-api"
        exclude group: "com.google.code.findbugs", module: "jsr305"
        exclude group: "org.jetbrains", module: "annotations"
        exclude group: "com.ibm.icu", module: "icu4j"
        exclude group: "it.unimi.dsi", module: "fastutil"
    }
    implementation("icyllis.modernui:ModernUI-Markflow:$rootProject.modernui_version") {
        exclude group: "org.slf4j", module: "slf4j-api"
        exclude group: "org.apache.logging.log4j", module: "log4j-core"
        exclude group: "org.apache.logging.log4j", module: "log4j-api"
        exclude group: "com.google.code.findbugs", module: "jsr305"
        exclude group: "org.jetbrains", module: "annotations"
        exclude group: "com.ibm.icu", module: "icu4j"
        exclude group: "it.unimi.dsi", module: "fastutil"
        exclude group: "org.commonmark"
    }

    implementation "com.sedmelluq:lavaplayer:$rootProject.lavaplayer_version"
    shadowBundle "com.sedmelluq:lavaplayer:$rootProject.lavaplayer_version"

    compileOnly "org.projectlombok:lombok:$rootProject.lombok_version"
    annotationProcessor "org.projectlombok:lombok:$rootProject.lombok_version"
    testCompileOnly "org.projectlombok:lombok:$rootProject.lombok_version"
    testAnnotationProcessor "org.projectlombok:lombok:$rootProject.lombok_version"
    testImplementation "org.junit.jupiter:junit-jupiter:$rootProject.junit_version"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"

//    implementation "io.github.selemba1000:JavaMediaTransportControls:$rootProject.jmtc_version"
//    shadowBundle "io.github.selemba1000:JavaMediaTransportControls:$rootProject.jmtc_version"
    implementation "com.github.hypfvieh:dbus-java-core:$rootProject.dbus_version"
    shadowBundle "com.github.hypfvieh:dbus-java-core:$rootProject.dbus_version"

    implementation "com.github.hypfvieh:dbus-java-transport-native-unixsocket:$rootProject.dbus_version"
    shadowBundle "com.github.hypfvieh:dbus-java-transport-native-unixsocket:$rootProject.dbus_version"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: inputs.properties.version
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
    exclude 'org/slf4j/**'
}

jar {
    dependsOn shadowJar
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from(zipTree(shadowJar.archiveFile))
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = base.archivesName.get()
            from components.java
        }
    }
}
