plugins {
    id 'java-library'
    id 'com.gradleup.shadow'
}

base {
    archivesName = "$rootProject.archives_name-velocity"
}

configurations {
    core {
        canBeResolved = true
        canBeConsumed = false
    }
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom core
    runtimeClasspath.extendsFrom core
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    core(project(path: ':core'))
    shadowBundle(project(path: ':core')) { transitive = false }

    compileOnly "com.velocitypowered:velocity-api:$rootProject.velocity_api_version"
    annotationProcessor "com.velocitypowered:velocity-api:$rootProject.velocity_api_version"
    compileOnly "io.netty:netty-buffer:$rootProject.netty_version"
    compileOnly "io.netty:netty-codec:$rootProject.netty_version"

    implementation "org.apache.logging.log4j:log4j-api:2.24.1"
    implementation "org.apache.logging.log4j:log4j-core:2.24.1"
    shadowBundle "org.apache.logging.log4j:log4j-api:2.24.1"
    shadowBundle "org.apache.logging.log4j:log4j-core:2.24.1"

    compileOnly "org.projectlombok:lombok:$rootProject.lombok_version"
    annotationProcessor "org.projectlombok:lombok:$rootProject.lombok_version"
    compileOnly project(':processor')
    annotationProcessor project(':processor')
    testImplementation "org.junit.jupiter:junit-jupiter:$rootProject.junit_version"
    testImplementation project(':core')
    testImplementation "com.velocitypowered:velocity-api:$rootProject.velocity_api_version"
    testImplementation "io.netty:netty-buffer:$rootProject.netty_version"
    testImplementation "io.netty:netty-codec:$rootProject.netty_version"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-Amusichud.module=velocity']
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

tasks.shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = ''
}

tasks.jar { archiveClassifier = 'plain' }

tasks.assemble {
    dependsOn tasks.shadowJar
}
