serverApiBaseUrl: "http://localhost:3000"
startupBinaryApiServerWhenLaunch: true
# Relative paths are resolved from plugins/MusicHud/
serverApiBinaryExecutablePath: "api"
pusherVoteAdditionalRate: 0.5
useRandomCnIp: true
