name: MusicHud
version: '${version}'
main: indi.etern.musichud.paper.CommonInitializer
api-version: '${apiVersion}'
description: A plugin allow to play music from NCM in whole server
authors: [Etern]
